### ISSUE TITLE
Details title bar doesn't auto-hide

### ISSUE THREAD

**Issue by comiluv** [Tercioo/Details-Damage-Meter#84] opened 2020-06-30 00:05 UTC
### **Before Start!**
**Make sure the bug also happen when Details! is the only addon enabled.**

**Game and Details! version**
Use /details to grab these two.
8.3.0 r7345

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
1) Set Details to use 'Serenity' skin
2) Set Details window to auto-hide when out of combat

- Result (what happens when you follow the steps above):
Details window auto hides but title bar doesn't hide

- Expected (what you think the expected behavior would be when following the steps):
Title bar hides when details window auto-hides

- When the bug started (a date, wow path release, details update, etc)?
r7345

- Additional information:

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*

**Screenshots**
Post images of the bug if necessary.
![detailsbug](https://user-images.githubusercontent.com/19642705/86067856-cfb55780-bab0-11ea-98af-29391f54fc6d.png)

**Combat Log**
Include a link to a combatlog file if the error is about not detecting a skill, usable item or item proc.
The log can be as simple as hitting a mob with white damage and using the item/skill.

**Other Information**
If necessary, add more info here.

**Comment by Tercioo** [comment] 2020-06-30 00:10
got it, thanks for reporting

------ Original Message ------

**Comment by SilentSigns** [comment] 2020-07-01 04:11
Adding to this (8.3.0 r7345), the issue is temporarily resolved by opening the Window:General>WindowColor color picker (no need to actually modify) or by modifying either Window:Automation>OnHoverOver or Window:Automation>NoInteraction sliders. Also interacts oddly with enabling/disabling the Window:Automation>AutoHide options.

Issue recurs when entering combat with or without any window automation enabled.

**Comment by Tercioo** [comment] 2020-07-01 13:33
See if the latest release DetailsRetail.8.3.0.7345a.141 
<https://www.curseforge.com/wow/addons/details/files/2993192> fixes the 
problem for you.

------ Original Message ------

**Closed** 2020-07-01 15:59 UTC
